creatures/urls.py
from django.urls import path

from . import views

app_name = "creatures"

urlpatterns = [
    path("opponents", views.IndexView.as_view(), name="index"),
    path(
        "<int:pk>",
        views.CreatureDetailView.as_view(),
        name="detail",
    ),
    path("hirelings", views.HirelingsView.as_view(), name="hirelings"),
    path("NPCs", views.NPCView.as_view(), name="NPCs"),
]

simple_auth/urls.py
from django.urls import path

from .views import register, login_request, logout_request

app_name = "simple_auth"

urlpatterns = [
    path("creer_compte", register, name="register"),
    path("identification", login_request, name="login"),
    path("deconnexion", logout_request, name="logout"),
]

spellburn_and_battlescars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("characters/", include("characters.urls")),
    path("npcs/", include("creatures.urls")),
    path("authentification/", include("simple_auth.urls")),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
]

handler404 = "spellburn_and_battlescars.views.page_not_found_view"
handler500 = "spellburn_and_battlescars.views.error_view"

simple_auth/models.py
from django.db import models

# Create your models here.

simple_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

simple_auth/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm


def register(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")

    return render(
        request=request,
        template_name="simple_auth/register.html",
        context={"register_form": form},
    )


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Welcome, {username}.")
                return redirect("index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(
        request=request,
        template_name="simple_auth/login.html",
        context={"login_form": form},
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("index")

simple_auth/templates/simple_auth/login.html
{% extends "base.html" %}
{% block title%}
Spellburn and Battlescars | Log in
{% endblock %}
{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
    <h1>Log in</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Log in</button>
    </form>
    <p class="text-center">You don't have an account yet? <a href="{% url 'simple_auth:register' %}">Sign in</a>.</p>
</div>

{% endblock %}

simple_auth/templates/simple_auth/register.html
{% extends "base.html" %}
{% block title%}
Spellburn and Battlescars | Sign in
{% endblock %}
{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
    <h1>Sign in</h1>
    <form method="POST">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Create account</button>
    </form>
    <p class="text-center">If you already have an account <a href="{% url 'simple_auth:login' %}">log in</a> instead.
    </p>
</div>

{% endblock %}