characters/urls.py
from django.urls import path

from . import views

app_name = "characters"

urlpatterns = [
    path("create_character", views.create_character, name="create_character"),
    path("my_characters", views.my_characters.as_view(), name="my_characters"),
    path(
        "my_characters/detail/<int:pk>",
        views.character_detail.as_view(),
        name="character_detail",
    ),
    path(
        "create_character/choose_origin/<int:pk>",
        views.choose_origin_view,
        name="choose_origin",
    ),
    path(
        "my_characters/delete/<int:pk>", views.delete_character, name="delete_character"
    ),
    path("scars", views.Scars.as_view(), name="scars"),
    path("magic/spells", views.Spells.as_view(), name="spells"),
    path("magic/mishaps", views.Mishaps.as_view(), name="mishaps"),
    path("magic/roll_spell", views.roll_spell_view, name="roll_spell"),
    path("equipment", views.Equipment.as_view(), name="equipment"),
]

creatures/urls.py
from django.urls import path

from . import views

app_name = "creatures"

urlpatterns = [
    path("opponents", views.IndexView.as_view(), name="index"),
    path(
        "<int:pk>",
        views.CreatureDetailView.as_view(),
        name="detail",
    ),
    path("hirelings", views.HirelingsView.as_view(), name="hirelings"),
    path("NPCs", views.NPCView.as_view(), name="NPCs"),
]

spellburn_and_battlescars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("characters/", include("characters.urls")),
    path("npcs/", include("creatures.urls")),
    path("authentification/", include("simple_auth.urls")),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
]

handler404 = "spellburn_and_battlescars.views.page_not_found_view"
handler500 = "spellburn_and_battlescars.views.error_view"

characters/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class Character(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = models.TextField(max_length=200)
    archetype = models.TextField(max_length=200)
    origin = models.TextField(max_length=400, null=True, blank=True)
    abilities = models.TextField(max_length=10, null=True, blank=True)
    background = models.TextField(max_length=200, null=True, blank=True)
    armor = models.SmallIntegerField(default=0, blank=True, null=True)
    hp = models.SmallIntegerField(default=0, blank=True, null=True)
    current_hp = models.SmallIntegerField(default=0, blank=True, null=True)
    body = models.SmallIntegerField(default=0, blank=True, null=True)
    mind = models.SmallIntegerField(default=0, blank=True, null=True)
    luck = models.SmallIntegerField(default=0, blank=True, null=True)
    gear = models.TextField()
    gold = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.name

characters/forms.py
from django import forms
from .archetypes import origins, triggers_dict, abilities_dict
from .spells import spell_choices


class CharacterCreationForm(forms.Form):
    name = forms.CharField(
        label="Name of the character. Leave empty for a random name.",
        max_length=100,
        required=False,
    )
    archetype_choices = (
        ("1", "Cleric"),
        ("2", "Fighter"),
        ("3", "Magic User"),
        ("4", "Thief"),
        ("5", "Dwarf"),
        ("6", "Elf"),
        ("7", "Halfling"),
        ("8", "Random"),
    )

    archetype = forms.ChoiceField(
        label="What archetype do you want to be?",
        choices=archetype_choices,
        required=True,
    )

    prioritize_body = forms.BooleanField(
        label="Do you want to prioritize BODY over MIND?",
        required=False,
    )


class ChooseOriginForm(forms.Form):
    origin = forms.ChoiceField(
        label="Origins: ",
        choices=[],
        required=True,
    )
    ability = forms.ChoiceField(
        label="Abilities: ",
        choices=[],
        required=True,
    )

    def __init__(self, archetype=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if archetype:
            self.fields["origin"].choices = origins.get(archetype).get("choices")
            self.fields["origin"].label += origins.get(archetype).get("prompt")
            self.fields["ability"].label += triggers_dict.get(archetype)
            self.fields["ability"].choices = abilities_dict.get(archetype)


class RollSpellForm(forms.Form):
    spell = forms.ChoiceField(choices=spell_choices)
    power = forms.IntegerField(
        min_value=1,
        max_value=5,
        label="How many dice do you want to invest?",
        required=True,
    )

characters/views.py
from random import randint, choice

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView, DetailView, TemplateView

from .models import Character
from .forms import CharacterCreationForm, RollSpellForm, ChooseOriginForm


from .roll import roll_stats, roll_spell_func

from .backgrounds import backgrounds
from .random_names import random_names
from .archetypes import (
    archetypes,
    origins,
    abilities_dict,
    triggers_dict,
    starting_gear_dict,
)

from .equipment import ARMOR, WEAPONS, GEAR_TOOLS
from .scars import scars
from .mishaps import mishaps
from .spells import spells, spell_names, spell_dict


@login_required
def create_character(request):
    if request.method == "POST":
        form = CharacterCreationForm(request.POST)
        if form.is_valid():
            # création du personnage proprement dit
            character = Character()
            character.archetype = CharacterCreationForm.archetype_choices[
                int(form.cleaned_data["archetype"]) - 1
            ][1]

            if character.archetype == "Random":
                character.archetype = choice(archetypes)

            character.name = form.cleaned_data["name"] or choice(
                random_names.get(character.archetype)
            )

            character.user = request.user

            character.hp = randint(1, 6)
            background, bg_gear = choice(backgrounds.get(character.hp))
            character.background = background

            character.gear = [
                bg_gear,
                "Three days’ Rations",
                "A Torch",
            ] + starting_gear_dict.get(character.archetype)
            prioritize_body = form.cleaned_data["prioritize_body"]
            body, mind, luck = roll_stats(prioritize_body=prioritize_body)
            character.body = body
            character.mind = mind
            character.luck = luck
            character.gold = 10
            # save the char
            character.save()

            # redirect to my characters or character detail
            # add a success message before
            messages.success(
                request,
                f"{character.name}, the {character.archetype} created. Now choose an origin.",
            )
            return HttpResponseRedirect(
                reverse("characters:choose_origin", args=[character.pk])
            )
    else:
        # build context with empty form
        context = {"form": CharacterCreationForm()}

    return render(request, "characters/create_character.html", context)


@login_required
def choose_origin_view(request, pk):
    character = Character.objects.get(pk=pk)
    # check if character.user and request.user match
    if character.user == request.user:
        # if we're in the POST method case
        if request.method == "POST":
            # create the filled form, with archetype to manage the prompt and the choices
            form = ChooseOriginForm(character.archetype, request.POST)

            if form.is_valid():
                origin_prompt = origins.get(character.archetype).get("prompt")
                # offset by 1 because the choices enumerate starting from 1 instead of 0
                choice_made = int(form.cleaned_data["origin"]) - 1
                origin_text = origins.get(character.archetype).get("choices")[
                    choice_made
                ][1]
                character.origin = f"<b>{origin_prompt}</b><br>{origin_text}"

                # add the chosen ability
                choice_made = int(form.cleaned_data.get("ability"))
                character.abilities = [int(choice_made)]

                character.save()
                messages.success(
                    request, f"Welcome, {character.name} the {character.archetype}."
                )
                return HttpResponseRedirect(reverse("characters:my_characters"))
            else:
                messages.warning(request, "invalid form?")
                return HttpResponseRedirect(reverse("characters:my_characters"))
        else:
            # build context with empty form with archetype to manage the prompt and the choices
            context = {"form": ChooseOriginForm(archetype=character.archetype)}
            return render(request, "characters/choose_origin.html", context)
    else:
        messages.warning(request, "This character is not yours")
        return HttpResponseRedirect(reverse("characters:my_characters"))


class my_characters(LoginRequiredMixin, ListView):
    model = Character
    # paginate_by = 10  # if pagination is desired
    template_name = "characters/my_characters.html"
    context_object_name = "characters"

    # redirect_field_name = "personnages/mes_personnages"

    def get_queryset(self):
        return Character.objects.filter(user=self.request.user)


class character_detail(LoginRequiredMixin, DetailView):
    model = Character
    template_name = "characters/character_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        archetype = context.get("character").archetype
        context.get("character").abilities = eval(context.get("character").abilities)
        context["triggers"] = triggers_dict.get(archetype)
        context["abilities"] = [ab[1] for ab in abilities_dict.get(archetype)]
        context["rows"] = list(range(5))
        inventory = eval(context.get("character").gear)
        empty_slots = ["" for _ in range(10 - len(inventory))]
        context["inventory"] = inventory + empty_slots
        return context


@login_required
def delete_character(request, pk):
    character = Character.objects.get(pk=pk)
    # check if character.user and request.user match
    if character.user == request.user:
        name = character.name
        character.delete()
        messages.success(request, f"Rest in peace, {name}.")
    else:
        messages.warning(request, "This characters is not yours.")

    return HttpResponseRedirect(reverse("characters:my_characters"))


class Scars(TemplateView):
    template_name = "characters/scars.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["scars"] = scars
        return context


class Mishaps(TemplateView):
    template_name = "characters/mishaps.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mishaps"] = mishaps
        return context


class Spells(TemplateView):
    template_name = "characters/spells.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["spells"] = spells
        return context


class Equipment(TemplateView):
    template_name = "characters/equipment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["armor"] = ARMOR
        context["weapons"] = WEAPONS
        context["tools"] = GEAR_TOOLS
        return context


def roll_spell_view(request):
    if request.method == "POST":
        form = RollSpellForm(request.POST)

        if form.is_valid():
            power = form.cleaned_data.get("power")
            spell_chosen = int(form.cleaned_data.get("spell"))

            spell_name = spell_names[spell_chosen]
            spell_effect = spell_dict[spell_name]

            DICE_LIST, SUM, DICE, FATIGUE, MISHAP = roll_spell_func(power)
            context = {
                "form": form,
                "SUM": SUM,
                "DICE_LIST": DICE_LIST,
                "DICE": DICE,
                "FATIGUE": FATIGUE,
                "MISHAP": MISHAP,
                "spell_name": spell_name,
                "spell_effect": spell_effect,
            }
            return render(request, "characters/roll_spell.html", context)
        # if a GET (or any other method) we'll create a blank form
    else:
        context = {"form": RollSpellForm()}
    return render(request, "characters/roll_spell.html", context)

characters/templates/characters/character_detail.html
{% extends "base.html" %}

{% block title %}
Spellburn and Battlescars | {{character.name}}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h1>{{character.name}}, the {{character.archetype}}</h1>


            <p>Former {{character.background}}</p>
            <h4>Ability scores</h4>
            <table class="table">
                <tr>
                    <th>♥️</th>
                    <th>🛡️</th>
                    <th>💪</th>
                    <th>🧠</th>
                    <th>🍀</th>
                </tr>
                <tr>
                    <td>{{character.hp}}/{{character.hp}}</td>
                    <td>{{character.armor}}</td>
                    <td>{{character.body}}/{{character.body}}</td>
                    <td>{{character.mind}}/{{character.mind}}</td>
                    <td>{{character.luck}}</td>
                </tr>

            </table>
            <h4>Origin:</h4>

            <p>{{character.origin|safe}}</p>

            <h4>Special abilities</h4>
            <p>{{triggers}}</p>
            <table class="table">
                {% for ability in abilities%}
                <tr>
                    {% if forloop.counter0 in character.abilities %}
                    <td>✅</td>
                    {% else%}
                    <td>☐</td>
                    {% endif %}
                    <td>
                        {{ability}}
                    </td>
                </tr>
                {%endfor%}
            </table>

            <table class="table">
                <tr>
                    <th>Inventory</th>
                    <th></th>
                </tr>
                {% for item in inventory %}
                <tr>
                    <td>{{forloop.counter}}: </td>
                    <td> {{item}}</td>

                </tr>
                {% endfor %}
            </table>
            <h5><b>GP:</b> {{character.gold}}</h5>
        </div>
    </div>
</div>

<a class='btn btn-danger float-right' role="button" href="{% url 'characters:delete_character' character.pk %}">⚰️
    Delete</a>


{% endblock %}

characters/templates/characters/choose_origin.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Spellburn and Battlescars | Choose origin
{% endblock %}

{% block content %}
<h1>Choose origin</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Tavern</a></li>
        <li class="breadcrumb-item active" aria-current="page">Create a Character</li>
    </ol>
</nav>
<br>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Select origin</button>
</form>

{% endblock %}

characters/templates/characters/create_character.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Spellburn and Battlescars | Create a Character
{% endblock %}

{% block content %}
<h1>Create a Character</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Tavern</a></li>
        <li class="breadcrumb-item active" aria-current="page">Create a Character</li>
    </ol>
</nav>
<br>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Create</button>
</form>

{% endblock %}

characters/templates/characters/edit_character.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Modifier un personnage
{% endblock %}

{% block content %}
<h1>Modifier un personnage</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Modifier un personnage</li>
    </ol>
</nav>
<br>
{{ render_form(form) }}
{% endblock %}

characters/templates/characters/equipment.html
{% extends "base.html" %}
{% load static%}

{% block title %}
Spellburn and Battlescars | Equipment
{% endblock %}

{% block content %}
<h1>Equipment Lists</h1>



<p><em>Prices in Gold Pieces</em></p>


<h2>Armor</h2>
<div class="container-fluid">
    <div class="row">

        <div class="col col-lg-8">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Armor</th>
                        <th>GP</th>
                    </tr>
                </thead>
                {% for name, cost in armor %}

                <tr>
                    <td>{{name}}</td>
                    <td>{{cost}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-auto"><img src="{% static 'characters/knight.png' %}" alt="a female knight clad in armor" />

        </div>
    </div>
</div>







<h2>Weapons</h2>
<div class="container-fluid">
    <div class="row">

        <div class="col col-lg-8">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Weapons</th>
                        <th>GP</th>
                    </tr>
                </thead>
                {% for name, cost in weapons %}

                <tr>
                    <td>{{name}}</td>
                    <td>{{cost}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-auto">
            <img src="{% static 'characters/equipment.png' %}" alt="a female rogue appraising a spiked maul" />
        </div>
    </div>
</div>


<h2>Gear & Tools</h2>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Gear & Tools</th>
            <th>GP</th>
        </tr>
    </thead>

    {% for name, cost in tools %}
    <tr>
        <td>{{name}}</td>
        <td>{{cost}}</td>
    </tr>
    {% endfor %}
</table>



{% endblock%}

characters/templates/characters/mishaps.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Spellburn and Battlescars | Mishaps
{% endblock %}

{% block content %}
<h1>Mishaps Table</h1>

<p>The GM can and should adapt these results according to the spell and
    character’s Background, adding color to the mechanical effects.</p>
<img src="{% static 'characters/mishap.png' %}" alt="spell caster with a giant eye globe as head" />
<table class="table table-striped">
    <thead>
        <tr>
            <th>SUM</th>
            <th>Description</th>
        </tr>
    </thead>
    {% for sum, mishap in mishaps.items %}

    <tr>
        <td>{{sum}}</td>
        <td>{{mishap}}</td>
    </tr>
    {% endfor %}
</table>



{% endblock%}

characters/templates/characters/my_characters.html
{% extends "base.html" %}

{% block title %}
Spellburn and Battlescars | My Characters
{% endblock %}

{% block content %}
<h1>My Characters</h1>
<br>
<div class="container">
    <div class="row">
        {% for char in characters %}
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'characters:character_detail' char.pk %}">
                            {{char.name}}</a>
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{char.archetype}}</h6>
                    <p class="card-text">Former {{char.background}}</p>
                    <table class="table">
                        <tr>
                            <th>♥️</th>

                            <th>💪</th>
                            <th>🧠</th>
                            <th>🍀</th>
                        </tr>
                        <tr>
                            <td>{{char.hp}}</td>

                            <td>{{char.body}}</td>
                            <td>{{char.mind}}</td>
                            <td>{{char.luck}}</td>
                        </tr>

                    </table>
                    <a class='btn btn-danger float-right' role="button"
                        href="{% url 'characters:delete_character' char.pk %}">
                        Delete</a>
                </div>
            </div>
            <br>
        </div>
        <br>
        {% endfor %}
    </div>
</div>



<br>


<a class="btn btn-primary" role="button" href="{% url 'characters:create_character' %}">Create a new character</a>
{% endblock %}

characters/templates/characters/roll_spell.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Casting a spell</h1>
<img class="float-right" src="{% static 'characters/casting_together.png' %}"
    alt="a wizard tutoring a warrior try to cast a spell" />
<p>
    To cast a spell, your character must hold a Grimoire or Scroll in both hands
    and read it aloud.</p>

<p>When your character Casts a Spell, decide on the <b>Power</b> to cast it with.<br>
    Starting Power can go up to your character’s available Inventory Slots, with
    a maximum of 5.</p>

<p><b>Roll a number of d6 equal to the Power chosen.</b> The spell has an effect,
    which varies depending on the number of <b>[DICE]</b> invested, and the <b>[SUM]</b>
    of the rolled dice. </p>

<ul>
    <li>For each [DICE] that shows 4 to 6, you suffer 1 Fatigue.</li>
</ul>

<p>If two or more [DICE] show the same number, <em>something has gone very wrong.</em>
    Find out what happened looking at the spell’s [SUM] on the Mishaps Table.</p>

<h2>Spell choice and Power Level</h2>
<form action="{% url 'characters:roll_spell' %}" method="post">
    {% csrf_token %}
    <table class="table table-striped">
        {{ form.as_table }}
    </table>

    <input type="submit" value="Roll the dice">
</form>


<br><br><br>

{% if SUM %}
<div class="alert alert-success">
    <h2>Results</h2>
    {% for d in DICE_LIST %}
    <img src="{% static 'characters/dice/' %}/{{d}}.png " alt="a die showing {{d}}" />
    {% endfor %}

    <ul>
        <li>SUM: {{SUM}}</li>
        <li>DICE: {{DICE}}</li>
        <li>FATIGUE: {{FATIGUE}}</li>

    </ul>
    <h3>{{spell_name}}</h3>
    <p>{{spell_effect}}</p>
</div>
{% if MISHAP %}
<div class="alert alert-danger">
    <h2>Oh no, there was a mishap!</h2>
    <p> {{MISHAP}}</p>
</div>
<br>
{% endif %}


{% endif %}


{% endblock %}

characters/templates/characters/scars.html
{% extends "base.html" %}{% load static %}

{% block title %}
Spellburn and Battlescars | Scars
{% endblock %}

{% block content %}
<h1>Scars</h1>

<img src="{% static 'characters/scar.png' %}" />
<p>If an attack takes you to exactly 0 HP, take a permanent Scar. Reference the total amount of Damage received with the
    table below:</p>
<table class="table table-striped">
    {% for dmg, scar in scars.items%}
    <tr>
        <td>{{dmg}}</td>
        <td>{{scar}}</td>
    </tr>
    {% endfor %}
</table>



{% endblock%}

characters/templates/characters/spells.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Spellburn and Battlescars | Mishaps
{% endblock %}

{% block content %}
<h1>List of Spells</h1>

<img class="rounded d-block" src="{% static 'characters/spell_books.png' %}"
    alt="spell books with a skull and a candle on top" />

<p>Example spells. Roll d66 on this table for a random Scroll as loot.
    If the spell isn’t instant and it doesn’t have a specified duration, it lasts 1 Turn.</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>d66</th>
            <th>Spell Name</th>
            <th>Effect</th>
        </tr>
    </thead>
    {% for spell in spells %}

    <tr>
        {% for v in spell.values %}
        <td>{{v}}</td>
        {% endfor %}

    </tr>
    {% endfor %}
</table>

<img class="rounded mx-auto d-block" src="{% static 'characters/casting.png' %}" alt="spell casters casting spells" />

{% endblock%}