characters/urls.py
from django.urls import path

from . import views

app_name = "characters"

urlpatterns = [
    path("create_character", views.create_character, name="create_character"),
    path("my_characters", views.my_characters.as_view(), name="my_characters"),
    path(
        "my_characters/detail/<int:pk>",
        views.character_detail.as_view(),
        name="character_detail",
    ),
    path(
        "create_character/choose_origin/<int:pk>",
        views.choose_origin_view,
        name="choose_origin",
    ),
    path(
        "my_characters/delete/<int:pk>", views.delete_character, name="delete_character"
    ),
    path("scars", views.Scars.as_view(), name="scars"),
    path("magic/spells", views.Spells.as_view(), name="spells"),
    path("magic/mishaps", views.Mishaps.as_view(), name="mishaps"),
    path("magic/roll_spell", views.roll_spell_view, name="roll_spell"),
    path("equipment", views.Equipment.as_view(), name="equipment"),
]

creatures/urls.py
from django.urls import path

from . import views

app_name = "creatures"

urlpatterns = [
    path("opponents", views.IndexView.as_view(), name="index"),
    path(
        "<int:pk>",
        views.CreatureDetailView.as_view(),
        name="detail",
    ),
    path("hirelings", views.HirelingsView.as_view(), name="hirelings"),
    path("NPCs", views.NPCView.as_view(), name="NPCs"),
]

simple_auth/urls.py
from django.urls import path

from .views import register, login_request, logout_request

app_name = "simple_auth"

urlpatterns = [
    path("creer_compte", register, name="register"),
    path("identification", login_request, name="login"),
    path("deconnexion", logout_request, name="logout"),
]

spellburn_and_battlescars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("characters/", include("characters.urls")),
    path("npcs/", include("creatures.urls")),
    path("authentification/", include("simple_auth.urls")),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
]

handler404 = "spellburn_and_battlescars.views.page_not_found_view"
handler500 = "spellburn_and_battlescars.views.error_view"

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">


<head>

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- our css -->
    <link rel="stylesheet" href="{% static 'creatures/styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🔥</text></svg>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <!-- Nav bar-->
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Spellburn and Battlescars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">🧙 Characters</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{% url 'characters:create_character' %}">Create a
                                character</a>
                            <a class="dropdown-item" href="{% url 'characters:my_characters' %}">My characters</a>

                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'characters:scars' %}">🤕 Scars</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'characters:equipment' %}">⚙️ Equipment</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">🔮 Magic</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{% url 'characters:spells' %}">📜 Spells List</a>
                            <a class="dropdown-item" href="{% url 'characters:mishaps' %}">💥 Mishaps Table</a>
                            <a class="dropdown-item" href="{% url 'characters:roll_spell' %}">🎲 Cast a spell</a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">💁 NPCs</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'creatures:NPCs' %}">🙋 NPCs generalities</a>
                            <a class="dropdown-item" href="{% url 'creatures:hirelings' %}">🙋 Hirelings</a>
                            <a class="dropdown-item" href="{% url 'creatures:index' %}">🧟 Opponents</a>
                        </div>
                    </li>



                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Edit my account</a>

                            <div class=" dropdown-divider">
                            </div>
                            <a class="dropdown-item" href="{% url 'simple_auth:logout' %}">Log out</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'simple_auth:login'%}">Login / Sign in<span
                                class="sr-only">(current)</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </nav>
    <br>
    <br>
    <br>
    <!--messages-->

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endblock %}

    <div class="container">
        <div id="content">
            {% block content %}{% endblock %}
            <br><br>
        </div>
    </div>
    {% block footer%}
    <br>
    <br>
    <br>
    <br>
    <br>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
        <div class="container-fluid">

            <span class="navbar-text"><a href="https://xenio-in-a-bottle.itch.io/sab" target="blank"><b>Spellburn
                        and
                        Battlescars</b></a> is a game
                by <a href="https://xenio-in-a-bottle.itch.io/" target="blank">Luís Fernando Anizello & Matheus
                    Henrique
                    Morais</a>, licensed under
                CC-BY-SA 4.0.<br>
                All art by Emiel Boven, please <a target="blank" href="https://www.patreon.com/emielboven">support the
                    artist</a>.</span>

        </div>
    </nav>
    {% endblock %}
    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>


    <!-- Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Spellburn and Battlescars
{% endblock %}

{% block content %}
<h1>Welcome,
    {% if user.is_authenticated %}
    {{user.username }}
    {% else %}
    Friend
    {% endif %}!
</h1>

<img width="60%" src="{% static 'characters/sab.png' %}">

<p>This is a simple tool to quickly generate characters, roll spells and mishaps, and consult tables and NPCs.</p>

{% endblock %}

templates/my_profile.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Modifier mon compte
{% endblock %}

{% block content %}
<h1>Modifier mon compte</h1>
<br></br>


{{ render_form(profileform) }}
{% endblock %}